apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-streams-kafka-topic
spec:
  destination:
    name: ''
    namespace: amq-streams-kafka-cluster
    server: 'https://kubernetes.default.svc'
  source:
    path: amq-streams-kafka-topic/base
    repoURL: 'https://github.com/snoussi/amq-streams-argocd'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true